# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0b2a22c84296e82eb0706f6eec5bbdca7dfae037fdd8df289cc97c5e2e6e2d3613aa12581dc8f2e5f31c7f225c0adad111585ca6cfe112557e4ebcbc22aedaf

test:
  secret_key_base: 4e430592ffd89557a8e4af1fae26264cd726cf0d725f32cd0a962aaef4369f28bf69324b85bb77c3fcb31aef8ae170f16f1a2743f5b9ffcdf5241ebb26599e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
